spring:
  datasource:
    url: jdbc:mysql://localhost/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true